name: compute_sum

on:
  workflow_dispatch:
    inputs:
      folder:
        description: 'folder parameter'
        required: true
        type: string
      input1:
        description: 'input1 parameter'
        required: true
        type: string
      input2:
        description: 'input2 parameter'
        required: true
        type: string
      output:
        description: 'output parameter'
        required: true
        type: string

jobs:
  run-function:
    runs-on: ubuntu-latest
    container: ghcr.io/faasr/github-actions-tidyverse
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: dekkov/FaaSr-tutorial-fork
