name: compute_sum

on:
  workflow_dispatch:
    inputs:
      folder:
        description: 'folder parameter'
        required: true
        type: string
        default: 'tutorial'
      input1:
        description: 'input1 parameter'
        required: true
        type: string
        default: 'sample1.csv'
      input2:
        description: 'input2 parameter'
        required: true
        type: string
        default: 'sample2.csv'
      output:
        description: 'output parameter'
        required: true
        type: string
        default: 'sum.csv'

jobs:
  run-function:
    runs-on: ubuntu-latest
    container: ghcr.io/faasr/github-actions-tidyverse
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: dekkov/FaaSr-tutorial-fork
      
      - name: Run R function
        run: |
          Rscript compute_sum.R ${{ github.event.inputs.folder }}
${{ github.event.inputs.input1 }}
${{ github.event.inputs.input2 }}
${{ github.event.inputs.output }}
